export const GET_ALL_COMMENT = 'GET_ALL_COMMENT';
export const GET_ALL_COMMENT_SAGA = 'GET_ALL_COMMENT_SAGA';
export const REMOVE_COMMENT = 'REMOVE_COMMENT'
export const UPDATE_COMMENT_SAGA = 'UPDATE_COMMENT_SAGA';
